config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  get 'users/new'

  root 'movies#index'

  resources :movies, only: [:new, :create, :show]
  resources :genres
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy], controller: 'session'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :movies

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :genre
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id].present?
      @current_user ||= User.find(session[:user_id])
    end
  end

  helper_method :current_user

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def show
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    if @genre.save
      redirect_to root_url, notice: 'Genre created'
    else
      render :new
    end
  end

  def destroy
    @genre.delete
    redirect_to root_url, notice: 'Genre deleted'
  end

  def edit
  end

  def update
    @genre.update_columns(genre_params)
    redirect_to root_url, notice: 'Genre Updated'
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  def set_genre
    @genre = Genre.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to root_url, notice: 'Movie created'
    else
      render :new
    end
  end


  def movie_params
    params.require(:movie).permit(:name, :genre_id)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create


    user = User.find_by(email: params[:session][:email])

    if user && user.authenticate(params[:session][:password])

      session[:user_id] = user.id

      redirect_to root_url, notice: 'Success!'
    else
      redirect_to new_session_url, alert: 'Failed!'
    end

  end

  def destroy
    session[:user_id] = nil
    @current_user = nil
    redirect_to root_url, notice: 'Success!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: 'Thanks for signing up!'
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/_form.html.erb
<%= form_for @genre do |f| %>

    <% if @genre.errors.any? %>
        <% @genre.errors.messages.each_key do |field| %>
            <% @genre.errors.messages[field].each do |msg| %>
                <%= "#{field} #{msg}" %>
            <% end %>
        <% end %>
    <% end %>

    <%= f.label :name %>:
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<%= form_for @genre do |f| %>

    <% if @genre.errors.any? %>
        <% @genre.errors.messages.each_key do |field| %>
            <% @genre.errors.messages[field].each do |msg| %>
                <%= "#{field} #{msg}" %>
            <% end %>
        <% end %>
    <% end %>

    <%= f.label :name %>:
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<% @movies.each do |movie| %>
    <h2> <%= movie.name %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mvdb</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <div id="wrapper-bgbtm">
    <div id="header">
      <div id="logo">
        <h1><a href="#">Wood Working </a></h1>

        <p>template design by <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>
        </p>
      </div>
    </div>
    <!-- end #header -->
    <div id="menu">
      <ul>
        <li class="current_page_item"><a href="#">Homepage</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photos</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Links</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
    <!-- end #menu -->
    <div id="page">
      <div id="page-bgtop">
        <div id="page-bgbtm">

          <% if current_user.present? %>
              <%= current_user.email %>
              <%= link_to 'Log out', session_path, method: :delete %>
          <% else %>
              <%= link_to 'Login', new_session_path %>
          <% end %>

          <% if current_user.present? %>

              <%= link_to 'New Genre', new_genre_path %>
              <br/>
              <%= link_to 'New Movie', new_movie_path %>
              <br/>

          <% end %>

          <%= flash[:notice] %>
          <hr/>

          <%= yield %>
          <div id="sidebar">
            <div id="search">
              <h2>Search</h2>

              <form method="get" action="">
                <fieldset>
                  <input type="text" name="s" id="search-text" size="15"
                         value="enter keywords here..."/>
                  <input type="submit" id="search-submit" value="GO"/>
                </fieldset>
              </form>
            </div>
            <ul>
              <li>
                <h2>Aliquam tempus</h2>

                <p>Mauris vitae nisl nec metus placerat perdiet est. Phasellus dapibus semper
                  consectetuer hendrerit.</p>
              </li>
              <li>
                <h2>Categories</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
              <li>
                <h2>Blogroll</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
              <li>
                <h2>Archives</h2>
                <ul>
                  <li><a href="#">Aliquam libero</a></li>
                  <li><a href="#">Consectetuer adipiscing elit</a></li>
                  <li><a href="#">Metus aliquam pellentesque</a></li>
                  <li><a href="#">Suspendisse iaculis mauris</a></li>
                  <li><a href="#">Urnanet non molestie semper</a></li>
                  <li><a href="#">Proin gravida orci porttitor</a></li>
                </ul>
              </li>
            </ul>
          </div>
          <!-- end #sidebar -->
          <div style="clear: both;">&nbsp;</div>
        </div>
      </div>
    </div>
    <!-- end #page -->
    <div id="footer">
      <p>Copyright (c) 2011 Sitename.com. All rights reserved. Design by <a
      href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>.</p>
    </div>
    <!-- end #footer -->
  </div>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>

    <% if @movie.errors.any? %>
        <% @movie.errors.messages.each_key do |field| %>
            <% @movie.errors.messages[field].each do |msg| %>
                <%= "#{field} #{msg}" %>
            <% end %>
        <% end %>
    <% end %>

    <%= f.label :name %>:
    <%= f.text_field :name %>

    <%= f.label :genre_id %>:
    <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "select one" %>

    <%= f.submit %>
<% end %>

app/views/movies/index.html.erb
<% @genres.each do |genre| %>
    <h2><%= link_to genre.name, genre %></h2>
    <% if current_user.present? %>
        <small><%= link_to 'Delete', genre, method: :delete,
                           data: {confirm: 'Are you sure?'} %></small>

        <small><%= link_to 'Edit', edit_genre_path(genre) %></small>

    <% end %>

<% end %>


<div id="content">

  <% @genres.each do |genre| %>
      <% genre.movies.each do |movie| %>
          <div class="post">
            <h2 class="title"><%= link_to movie.name, movie %></h2>
            <%= link_to genre.name, genre %></h2>

            <p class="meta">Posted by <a href="#">Someone</a> on July 8, 2011
              &nbsp;&bull;&nbsp; <a href="#" class="comments">Comments (64)</a> &nbsp;&bull;&nbsp; <a
            href="#" class="permalink">Full article</a></p>

            <div class="entry">
              <p>
                <%= image_tag 'img02.jpg', size: '143x143', alt: 'hello' %>

                Sed lacus. Donec lectus. Nullam pretium nibh ut
                turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus.
                Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est.
                Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Sed
                lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor,
                elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat
                consectetuer. </p>
            </div>
          </div>
      <% end %>
  <% end %>
</div>
<!-- end #content -->

app/views/session/new.html.erb
<%= form_for :session, url: session_path do |form| %>

    <%= form.text_field :email, placeholder: 'email' %>
    <%= form.password_field :password, placeholder: 'password' %>
    <%= form.submit "Login" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <% @user.errors.messages.each_key do |field| %>
            <% @user.errors.messages[field].each do |msg| %>
                <%= "#{field} #{msg}" %>
            <% end %>
        <% end %>
    <% end %>

    Email: <%= f.text_field :email %> <br/>
    Password: <%= f.password_field :password %>  <br/>
    Password Confirmation: <%= f.password_field :password_confirmation %>  <br/>


    <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>